# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# isoScript.py
# Created on: 2021-03-04 03:37:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

import os

path = 'D:/shorelineMappingProject/photos1950'

folder = os.fsencode(path)

#filenames = []

for file in os.listdir(folder):
    filename = os.fsdecode(file)
    if filename.endswith( ('.tif') ): # whatever file types you're using...
        #filenames.append(filename)
        if filename.endswith(("composite1939.tif")):
            break
        else:
            dir_path = (os.path.dirname(os.path.realpath(__file__))) + "/photos1950/"
            stringPath = dir_path.replace("\\","/")
            #print(string)
            inputRasterPath = str(stringPath + filename)
            print("Input: ", inputRasterPath)
            parts = filename.split('.')
            outputRasterFile = ("".join(parts[:-1])+ '_ISO' + '.' + parts[-1])
            outputRasterPath = str(stringPath + outputRasterFile)
            Output_signature_file = ""
            print("Output: ",outputRasterPath)
            arcpy.gp.IsoClusterUnsupervisedClassification_sa(inputRasterPath, "2", outputRasterPath, "20", "10", Output_signature_file)
            print("\n Done. " + outputRasterFile + " has been created. \n")
        #else:
        #break



#print(filenames)
#filenames.sort() # now you have the filenames and can do something with them

# Local variables:
#v45043_1939_0003_0084_x_09_tif = "D:/shorelineMappingProject/photos1939/45043_1939_0003_0084_x_09.tif"
#v45043_1939_0003_0094_x_09_tif = "D:/shorelineMappingProject/photos1939/45043_1939_0003_0094_x_09.tif"
#c45043_1939_0003_0084_x_09_I = "C:/Users/zeebk/Documents/ArcGIS/Default.gdb/c45043_1939_0003_0084_x_09_I"
#Output_signature_file = ""

# Process: Iso Cluster Unsupervised Classification
#arcpy.gp.IsoClusterUnsupervisedClassification_sa(v45043_1939_0003_0084_x_09_tif, "3", c45043_1939_0003_0084_x_09_I, "20", "10", Output_signature_file)

