# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# polygonToLineScript.py
# Created on: 2021-03-04 21:26:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
#import arcpy


# Local variables:
#v45043_1939_0002_0066_x_09_ISO_VECTOR_shp = "D:\\shorelineMappingProject\\photos1939\\45043_1939_0002_0066_x_09_ISO_VECTOR.shp"
#LINETEST_shp = "D:\\shorelineMappingProject\\photos1939\\LINETEST.shp"

# Process: Feature To Line
#arcpy.FeatureToLine_management("D:\\shorelineMappingProject\\photos1939\\45043_1939_0002_0066_x_09_ISO_VECTOR.shp", LINETEST_shp, "", "ATTRIBUTES")

import arcpy
from arcpy import env
from arcpy.sa import *

import os

path = 'D:/shorelineMappingProject/photos1939'

folder = os.fsencode(path)

#filenames = []

for file in os.listdir(folder):
    filename = os.fsdecode(file)
    if filename.endswith( ('VECTOR.shp') ): # whatever file types you're using...
        #filenames.append(filename)
        #if filename.endswith(("12_ISO_VECTOR.shp")):
            #break
        #else:
        dir_path = (os.path.dirname(os.path.realpath(__file__))) + "/photos1939/"
        stringPath = dir_path.replace("\\","/")
        #print(string)
        inputPolygon = str(stringPath + filename)
        print("Input: ", inputPolygon)
        #polygonResult = str(stringPath + 
        parts = filename.split('.')
        lineResultName = ("".join(parts[:-1])+ '_LINE' + '.shp')
        #+ parts[-1])
        lineResult = str(stringPath + lineResultName)
        #Output_signature_file = ""
        print("Output: ",lineResult)
        #arcpy.RasterToPolygon_conversion(inputPolygon, lineResult, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")
        arcpy.PolygonToLine_management(inputPolygon, lineResult, "IDENTIFY_NEIGHBORS")
        
        print("\n Done. " + lineResultName + " has been created. \n")
# Local variables:
#inputISO = "D:\\shorelineMappingProject\\photos1939\\45043_1939_0002_0060_x_09_ISO.tif"
#polygonResult = "C:\\Users\\zeebk\\Documents\\ArcGIS\\Default.gdb\\RasterT_tif1"

# Process: Raster to Polygon
#arcpy.RasterToPolygon_conversion(inputISO, polygonResult, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")


