# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# rasterToPolygonScript.py
# Created on: 2021-03-04 04:58:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

import os

path = 'D:/shorelineMappingProject/photos1939'

folder = os.fsencode(path)

#filenames = []

for file in os.listdir(folder):
    filename = os.fsdecode(file)
    if filename.endswith( ('ISO.tif') ): # whatever file types you're using...
        #filenames.append(filename)
        #if filename.endswith(("12_ISO.tif")):
        #    break
        #else:
        dir_path = (os.path.dirname(os.path.realpath(__file__))) + "/photos1939/"
        stringPath = dir_path.replace("\\","/")
        #print(string)
        inputISO = str(stringPath + filename)
        print("Input: ", inputISO)
        #polygonResult = str(stringPath + 
        parts = filename.split('.')
        polygonResultName = ("".join(parts[:-1])+ '_VECTOR' + '.shp')
        #+ parts[-1])
        polygonResult = str(stringPath + polygonResultName)
        #Output_signature_file = ""
        print("Output: ",polygonResult)
        arcpy.RasterToPolygon_conversion(inputISO, polygonResult, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")
        print("\n Done. " + polygonResultName + " has been created. \n")
# Local variables:
#inputISO = "D:\\shorelineMappingProject\\photos1939\\45043_1939_0002_0060_x_09_ISO.tif"
#polygonResult = "C:\\Users\\zeebk\\Documents\\ArcGIS\\Default.gdb\\RasterT_tif1"

# Process: Raster to Polygon
#arcpy.RasterToPolygon_conversion(inputISO, polygonResult, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")

